- name: create a directory for prometheus (CentOS)
  file:
    path: ~/prometheus
    state: directory

- name: prometheus Download (CentOS)
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
    dest: ~/prometheus
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Executables(CentOS)
  shell: |
    cd ~/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus
 
- name: Setup Service File(CentOS)
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    mode: 0755
    owner: root
    group: root

- name: starting and enabling prometheus (CentOS)
  systemd: 
    name: prometheus
    state: started
    daemon_reload: true
    enabled: true
